# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/EDGE Contraint files/EDGE_A7.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_display_ctrl_0_0/design_1_display_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_display_ctrl_0_0 || ORIG_REF_NAME==design_1_display_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_main_0_1/design_1_main_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_main_0_1 || ORIG_REF_NAME==design_1_main_0_1} -quiet] -quiet

# XDC: c:/Users/Carlton/DigitalSystemDesignBook/ch7_3_SevenSegDisp/ch7_3_SevenSegDisp.gen/sources_1/bd/design_1/design_1_ooc.xdc
